@startuml
skinparam dpi 400

abstract Hierachial {
    Preserving exisiting\nDNS Structure 
}
abstract Decentralised {
    Radical DNS\narchitecture change
}
abstract Encipherment {

}
abstract Redaction {
    Minimise information leaks
}
abstract TransportChannel {

}
abstract CurrentStandards {
    Reusing DNS\nover exisiting secure protocols
}
abstract NewChannelMethod {
    Reusing DNS over\nown-implemented secure protocols
}
class DoT {
    standarised = "T"
}
class DoH {
    standarised = "T"
}
class Namecoin {
    standarised = "F"
}
class GNUNet {
    standarised = "F"
}
class ObliviousDNS{
    standarised = "F"
}
class QNAMEMinimization{
    standarised = "T"
}
class DTLS{
    standarised = "T"
}
class DNSCrypt{
    standarised = "F"
}
class DNSCurve{
    standarised = "F"
}

Hierachial -- Encipherment
Hierachial -- Redaction

Encipherment -- TransportChannel
TransportChannel -- CurrentStandards
TransportChannel -- NewChannelMethod

CurrentStandards <|-- DoT
CurrentStandards <|-- DoH
CurrentStandards <|-- DTLS

Redaction <|-- ObliviousDNS
Redaction <|-- QNAMEMinimization

NewChannelMethod <|-- DNSCrypt
NewChannelMethod <|-- DNSCurve

Decentralised <|-- Namecoin
Decentralised <|-- GNUNet

@enduml