@startuml
skinparam dpi 400
object User {
    IP address = "194.47.111.x"
}

object Resolver {
    Cached = "False"
}
object WHOIS {
    country = "SE"
    netname = "VAXJO-NET"
    descr = "Linnaeus University"
    mnt-lower = "SUNET-MNT"
}

object DNSquery {
    Request Name = "generate-spam.kr"
    Request Type = "MX record"
}

object circumstance {
    time = "YY-MM-DD HH:MM (TZ)"
    frequency = "First time"

}

User <|-- WHOIS
DNSquery -left- User
DNSquery -down- Resolver
Resolver <|-right- circumstance

@enduml